services:
  mongo:
    image: mongo:4.2.5
  myapp3:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    container_name: flask_nginx_service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - .:/var/www/logs
    depends_on:
      - myapp3
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  mongo_data:
  nginx_logs: